"""init

Revision ID: b9cd50049519
Revises: f8db662f8193
Create Date: 2025-05-31 23:21:30.219635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cd50049519'
down_revision: Union[str, None] = 'f8db662f8193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['telegram_user_id'])
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'telegram_user_id')
    # ### end Alembic commands ###
